inne_eddy:
  adapter: sqlite3
  database: inne_eddy.db
  host: localhost
  token: NTM1NjM0MTMwNDM2NjIwMjk4.DyLAJQ.2NgPYzYqJO9NLIGE2sb_v0HP07Q
  client_id: 535634130436620298
  level_update_frequency: 60
  episode_update_frequency: 460

development:
  adapter: sqlite3
  database: inne-dev.db
  host: localhost
  token: Mjk2MjE3NTkyODA3NDI0MDAw.C7vBqA.2N95P6C0RMnYkdPobKvao4thJ3g
  client_id: 296217592807424000
  level_update_frequency: 60
  episode_update_frequency: 460

production:
  adapter: sqlite3
  database: inne.db
  host: localhost
  token: Mjg5MTQxNzc2MjA2MjY2MzY5.C6IDyQ.1B1a2x_k7CF4UfaGWvhbGFVqdqM
  client_id: 289141776206266369

test:
  adapter: sqlite3
  database: inne-test.db
  host: localhost
  level_update_frequency: 1
  episode_update_frequency: 5
